version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "cargo"
    directory: "/examples/"
    schedule:
      interval: "weekly"
      day: "saturday"