language: rust

rust:
- stable

os:
- linux
- osx
- windows

stages:
- check
- test
- benchmark

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libssl-dev

jobs:
  allow_failures:
  - name: coverage # FIXME

  include:
  - name: fmt
    stage: check
    rust: stable
    os: linux
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: clippy
    stage: check
    rust: stable
    os: linux
    install:
    - rustup component add clippy
    script:
    - cargo clippy --all-targets -- -D warnings

  - name: coverage
    stage: check
    rust: nightly
    os: linux
    install:
    - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin
    script:
    - cargo +nightly tarpaulin -v --all-features --out Xml
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - name: doc
    stage: check
    rust: nightly
    os: linux
    script:
    - cargo +nightly doc --all-features

  - stage: test
    rust: nightly
    os: linux
    script:
    - cargo +nightly test -v --all-features

  - stage: test
    rust: nightly
    os: osx
    script:
    - cargo +nightly test -v --all-features

  - stage: test
    rust: nightly
    os: windows
    script:
    - cargo +nightly test -v --all-features

  - stage: benchmark
    if: type = pull_request
    rust: nightly
    os: linux
    script:
    - cargo bench --all-features
