name: CD

on:
  release:
    types: [published, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      if: !github.event.release.draft
