name: CD

on: [release]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable
    - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
      if: >-
        github.event_name == 'release' && !github.event.release.draft && (
          github.event.action == 'prereleased' ||
          github.event.action == 'published'
        )
